### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Lackym** [Lackym/WebonFramework#1]
# Todo:

- [ ] Parse http request to `webon::request` object in `webon::http_protocol::parse_request` method;
- [ ] Add timeout when reading new http requests in `webon::server::start_read`;
- [ ] Replace `std::array<char, 2048>` with unbounded read buffer in `webon::server::start_read`;
- [ ] Add abstraction to work with http cookies. It should be a part of `webon::request`;
- [ ] Add Unit Tests;
- [ ] Add FastCGI support by implementing `webon::fcgi_protocol : public webon::i_data_protocol`;
